// Bump this whenever PRIVACY_SECTIONS changes — Play/App Store reviewers
// and users both rely on this to know the policy is current, not stale.
export const PRIVACY_LAST_UPDATED = "August 21, 2026";

export interface PrivacyBlock {
  type: "p" | "ul" | "p-link";
  text?: string;
  items?: string[];
  /** "p-link" only — an inline link appended after `text`, e.g. the
   * dedicated account-deletion page (see Google Play's Data Deletion
   * requirement, which expects this reachable outside the app too). */
  linkHref?: string;
  linkLabel?: string;
}

export interface PrivacySection {
  number: number;
  heading: string;
  blocks: PrivacyBlock[];
}

const p = (text: string): PrivacyBlock => ({ type: "p", text });
const ul = (items: string[]): PrivacyBlock => ({ type: "ul", items });
const pLink = (text: string, linkHref: string, linkLabel: string): PrivacyBlock => ({
  type: "p-link",
  text,
  linkHref,
  linkLabel,
});

// Plain-language privacy policy, written to be clear and responsible rather
// than exhaustive legal drafting — intended for legal review before launch,
// not as a final lawyer-approved policy (see docs note in the page file).
export const PRIVACY_SECTIONS: PrivacySection[] = [
  {
    number: 1,
    heading: "What data Tistra collects",
    blocks: [
      p("To provide the Service, Tistra collects:"),
      ul([
        "Meal photos you or a family member/client send on WhatsApp.",
        "WhatsApp messages related to meal logging (e.g. captions, corrections, replies to the bot).",
        "Captions and notes you add to a meal.",
        "Basic account information (name, phone number, email, and similar details you provide when signing up or adding a contact).",
        "Meal classifications generated by Tistra (the food items, patterns, and summaries derived from what you share).",
        "Usage data (e.g. how you use the dashboard, which features you open).",
      ]),
    ],
  },
  {
    number: 2,
    heading: "How Tistra uses this data",
    blocks: [
      p("Tistra uses the data above to:"),
      ul([
        "Classify meals shared on WhatsApp.",
        "Generate food pattern insights (e.g. protein consistency, balanced plates, weekly trends).",
        "Provide dashboard summaries to you.",
        "Support family or coach sharing — but only based on the consent and sharing preferences of the person being tracked.",
        "Improve the quality and accuracy of the product over time.",
      ]),
    ],
  },
  {
    number: 3,
    heading: "AI processing",
    blocks: [
      p("Meal photos and messages may be processed by AI models (including third-party AI providers) to identify foods and generate summaries."),
      p("AI outputs may be imperfect — food identification, classifications, and suggestions are estimates, not guarantees of accuracy."),
      p("Tistra may store AI classification results (the structured output describing a meal) alongside the original submission."),
    ],
  },
  {
    number: 4,
    heading: "Human review",
    blocks: [
      p("Some meal photos and classifications may be reviewed by authorized Tistra team members for quality control — for example, to check whether the AI correctly identified a meal, or to improve how Tistra recognizes Indian food patterns over time."),
      p("Reviewers only see the information needed to review classification quality (e.g. the meal photo, caption, and AI output) — not your full name, phone number, payment details, or family relationship details. See our internal Meal Review Console design principles, which are built around this same limitation."),
    ],
  },
  {
    number: 5,
    heading: "Family sharing",
    blocks: [
      p("Family members only see the information the tracked person has consented to share. Sharing preferences (e.g. pausing sharing, choosing what a summary includes) are controlled by that person, not by whoever added them."),
      p("Tistra is designed for support, not surveillance — a family member cannot see anything the tracked person hasn't agreed to share."),
    ],
  },
  {
    number: 6,
    heading: "Coach/client visibility",
    blocks: [
      p("Coaches may see meal trends and summaries for clients who have joined their workspace or otherwise given permission to share."),
      p("Coaches should not receive unrelated personal data beyond what's needed for nutrition coaching (e.g. not payment details for other clients, not a client's family/relationship information)."),
    ],
  },
  {
    number: 7,
    heading: "Model improvement and consent",
    blocks: [
      p("Tistra may use reviewed meal photos and classifications to improve its underlying food-recognition and coaching models over time."),
      p("Where required, this is based on your consent — for example, a consent flag recorded at the time a meal is submitted, which defaults to off until explicitly enabled."),
      p("Tistra aims to anonymize or minimize identifiable data (e.g. removing names, phone numbers, and other direct identifiers) when meal data is used for product improvement."),
    ],
  },
  {
    number: 8,
    heading: "Data deletion and export",
    blocks: [
      p("You can request deletion of your data, or request access to / export of the data Tistra holds about you, by contacting us using the details in the Contact section below. We will respond within a reasonable timeframe and explain any limits (for example, data we're required to retain for legal or accounting reasons)."),
      pLink("For step-by-step instructions on requesting account deletion, see our", "/delete-account", "Delete Your Account page"),
    ],
  },
  {
    number: 9,
    heading: "Data sharing with others",
    blocks: [
      ul([
        "Tistra does not sell user data.",
        "Tistra does not use meal data for advertising.",
        "Tistra may use trusted service providers for hosting, WhatsApp messaging, AI processing, analytics, or payments — these providers process data on Tistra's behalf and are not permitted to use it for their own purposes.",
      ]),
    ],
  },
  {
    // Required by Google before an app requesting a Calendar scope can be
    // verified: the policy has to state what Google user data is accessed,
    // why, how it is stored and shared, and how to revoke it — and it must
    // carry the Limited Use sentence verbatim. Its absence is the most
    // common reason verification is refused.
    number: 10,
    heading: "Google Calendar (Tistra Coach)",
    blocks: [
      p("Coaches using Tistra Coach can connect a Google Calendar so that Tistra does not offer clients a session time the coach is already busy. Connecting is optional, and the rest of Tistra Coach works without it."),
      p("Tistra requests a single Google permission: calendar.freebusy. That permission returns only the start and end times of periods marked busy. It does not give Tistra access to event titles, descriptions, guests, locations, attachments, or any other calendar content — Tistra never asks Google for them, so they never reach us."),
      ul([
        "What we receive: busy time ranges from the coach's primary calendar, for the period being scheduled.",
        "What we use it for: hiding times the coach is already busy from their availability, and nothing else.",
        "Storage: the access and refresh tokens Google issues are encrypted before being stored. Busy times are held briefly in memory to avoid repeated calls and are not saved as calendar records.",
        "Sharing: busy times are never sold, never used for advertising, never used to train AI models, and are not shared with other users. A client booking a session sees only which times are unavailable, never why.",
        "Revoking: disconnecting Google Calendar in Tistra Coach settings deletes the stored tokens immediately. Access can also be revoked at any time from the coach's Google Account permissions page.",
      ]),
      pLink(
        "Tistra's use and transfer of information received from Google APIs to any other app adheres to the Google API Services User Data Policy, including the Limited Use requirements. The policy is available at",
        "https://developers.google.com/terms/api-services-user-data-policy",
        "Google API Services User Data Policy"
      ),
    ],
  },
  {
    number: 11,
    heading: "Security",
    blocks: [
      p("Data is stored securely using industry-standard practices. Access to personal data is limited to authorized Tistra personnel who need it to operate or improve the Service."),
    ],
  },
  {
    number: 12,
    heading: "Cross-border data transfers",
    blocks: [
      p("Tistra is based in Singapore, and users may be located in India or other markets. As a result, your data may be processed in countries other than the one you live in, by Tistra or its service providers, in order to provide the Service."),
    ],
  },
];
