-- "Today's Focus" morning recommendation feature — extends the existing
-- breakfast reminder (see src/app/api/cron/send-meal-reminders/route.ts)
-- with one short, personalized nutritional suggestion. Mirrors the
-- reminders_enabled/reminder_times per-contact preference pattern already
-- on adults_contacts/gym_clients (see 0016_meal_reminders.sql) rather than
-- introducing a separate notification-preferences table.

alter table adults_contacts add column if not exists todays_focus_enabled boolean not null default true;
alter table adults_contacts add column if not exists todays_focus_frequency text not null default 'daily'
  check (todays_focus_frequency in ('daily', 'weekdays', 'meaningful_only'));
alter table adults_contacts add column if not exists todays_focus_style text not null default 'concise'
  check (todays_focus_style in ('concise', 'explanatory'));

alter table gym_clients add column if not exists todays_focus_enabled boolean not null default true;
alter table gym_clients add column if not exists todays_focus_frequency text not null default 'daily'
  check (todays_focus_frequency in ('daily', 'weekdays', 'meaningful_only'));
alter table gym_clients add column if not exists todays_focus_style text not null default 'concise'
  check (todays_focus_style in ('concise', 'explanatory'));

-- One row per Today's Focus recommendation actually generated (whether or
-- not it was ultimately delivered) — doubles as: (a) the idempotency
-- record for the scheduled morning send (see the partial unique index
-- below), (b) repetition-control history (don't repeat the same category
-- on consecutive days), and (c) the feedback/admin-debug record. Mirrors
-- food_balance_score_snapshots' contact_id/contact_type shape
-- (0027_food_balance_score.sql) rather than inventing a new convention.
create table if not exists todays_focus_recommendations (
  id uuid primary key default gen_random_uuid(),
  contact_id uuid not null,
  contact_type text not null check (contact_type in ('adults_contact', 'gym_client')),
  workspace_id uuid not null references workspaces(id) on delete cascade,
  local_date date not null,
  timezone text not null,
  category text not null,
  priority_score numeric not null default 0,
  confidence text not null check (confidence in ('high', 'moderate', 'low')),
  analysis_window_days integer not null default 7,
  supporting_metrics jsonb not null default '{}'::jsonb,
  goal text,
  message_variant text,
  message_text text not null,
  suggested_food_ids text[] not null default '{}',
  -- True for the one recommendation generated by the scheduled morning
  -- job; false for a "change focus" follow-up (see conversation-handler.ts)
  -- — only scheduled rows are subject to the one-per-day idempotency
  -- guard below, since a change-focus reply intentionally adds a second
  -- recommendation for the same local_date.
  is_scheduled boolean not null default true,
  delivery_status text not null default 'pending' check (delivery_status in ('pending', 'sent', 'failed', 'skipped')),
  feedback text check (feedback in ('helpful', 'not_relevant', 'change_focus')),
  feedback_at timestamptz,
  created_at timestamptz not null default now()
);

-- The actual idempotency guard for the scheduled morning send — mirrors
-- meal_reminder_sends' unique index (0016_meal_reminders.sql): insert
-- before sending, and let a conflicting insert (a retried/overlapping
-- cron tick) be the signal to skip rather than send a duplicate message.
create unique index if not exists todays_focus_recommendations_scheduled_once_per_day
  on todays_focus_recommendations (contact_id, contact_type, local_date)
  where is_scheduled;

create index if not exists todays_focus_recommendations_contact_history_idx
  on todays_focus_recommendations (contact_id, contact_type, created_at desc);
