const path = require('path');
const fs = require('fs');
const { withDangerousMod, withAndroidManifest, AndroidConfig } = require('@expo/config-plugins');

// expo-dynamic-app-icon (v1.2.0, unmaintained) writes each dynamic icon as a
// plain bitmap into mipmap-{m,h,x,xx,xxx}dpi and points the generated
// <activity-alias android:icon="@mipmap/<name>"> at it. It never emits an
// adaptive-icon XML, so on Android 8+ every dynamic variant is a *legacy*
// icon — launchers shrink the bitmap and composite it on a white backdrop
// masked to the device shape (the original "bowl in a small square inside a
// white circle" report).
//
// This plugin adds the missing mipmap-anydpi-v26/<name>.xml for each variant
// so Android treats them as adaptive icons like the default one.
//
// CRITICAL NAMING CONSTRAINT (learned the hard way — the first version of
// this plugin pointed both layers at @mipmap/<name>, the same name as the
// XML itself): on API 26+ the anydpi-v26 XML *shadows* the density PNGs for
// that resource name, so a layer reference back to @mipmap/<name> resolves
// to the very XML being inflated — a circular reference. Android fails the
// inflate and every launcher silently falls back to the APPLICATION icon,
// which is why all four bowl variants rendered as the default white-sprigs
// art from build 35 through 36 no matter which alias was enabled (verified
// on-device: component state said bowl_half, screen showed default art,
// and neither a launcher restart nor a full reboot changed it). The layers
// must reference a DIFFERENTLY-NAMED resource, exactly like the stock
// ic_launcher.xml references ic_launcher_foreground/_background.
//
// So this plugin copies each variant's source image to
// drawable-nodpi/<name>_base.png and points both layers there.
// drawable-nodpi is deliberate twice over: expo-dynamic-app-icon's cleanup
// pass deletes every non-"ic_launcher*" file from the five mipmap density
// folders on each prebuild (so copies there could be swept depending on
// plugin order), and it never touches drawable-nodpi or mipmap-anydpi-v26.
// Both layers point at the same full-bleed opaque square, mirroring how the
// default icon is configured (its foreground and background images are
// byte-identical files).

const ANYDPI_FOLDER = ['app', 'src', 'main', 'res', 'mipmap-anydpi-v26'];
const NODPI_FOLDER = ['app', 'src', 'main', 'res', 'drawable-nodpi'];

/** Expo's own icon step writes this from adaptiveIcon.monochromeImage; only
 * referenced when the app actually configures one, since pointing at a
 * missing drawable is a hard resource-linking failure at build time. */
const MONOCHROME_RESOURCE = 'ic_launcher_monochrome';

function adaptiveIconXml(iconName, includeMonochrome) {
  const monochromeLine = includeMonochrome
    ? `\n    <monochrome android:drawable="@mipmap/${MONOCHROME_RESOURCE}"/>`
    : '';
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by apps/mobile/plugins/withAdaptiveDynamicIcons.js — do not edit by hand. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/${iconName}_base"/>
    <foreground android:drawable="@drawable/${iconName}_base"/>${monochromeLine}
</adaptive-icon>
`;
}

/** Accepts the same prop shape expo-dynamic-app-icon does (a record of
 * name -> { image }, or an array), so the icon set stays declared in one
 * place in app.json rather than duplicated here. Unlike the first version,
 * the image paths are REQUIRED — this plugin copies each image to the
 * <name>_base resource the adaptive XML references. */
function iconsFromProps(props) {
  if (!props) return [];
  if (Array.isArray(props)) return props.map((entry, i) => [String(i), entry?.image]);
  return Object.entries(props).map(([name, entry]) => [name, entry?.image]);
}

// ---------------------------------------------------------------------------
// Deep links must survive an icon change.
//
// expo-dynamic-app-icon switches icons by enabling an <activity-alias> and
// DISABLING .MainActivity (see its withDynamicIcon.js — the aliases it emits
// carry MAIN/LAUNCHER and nothing else). Every deep-link intent-filter lives
// on .MainActivity, so the moment a user's icon changed, tistramobile:// URIs
// stopped resolving on that device:
//
//   disabled: .MainActivity            <- owns the tistramobile:// filter
//   enabled:  .MainActivitybowl_half
//   $ am start -d "tistramobile://auth/callback"
//   Error: unable to resolve Intent
//
// That silently broke Google/Facebook OAuth, the email-confirmation link and
// password reset, for anyone who had logged meals for long enough to change
// their icon. No error was shown — expo-web-browser simply waits forever for
// a redirect that can never arrive. Confirmed on a Pixel 8 Pro running
// build 40 via adb dumpsys.
//
// So every alias gets a copy of MainActivity's own deep-link filters. Copied
// rather than hardcoded: the scheme set is whatever the app config and
// expo-router put there (tistramobile and exp+tistra-mobile today), and a
// hardcoded list would drift the next time either changes.

/** True for an intent-filter that routes a URI, i.e. carries <data>. The
 * MAIN/LAUNCHER filter has none, and must not be duplicated — two launcher
 * entries per alias would show duplicate icons. */
function isDeepLinkFilter(filter) {
  return Array.isArray(filter?.data) && filter.data.length > 0;
}

function withDeepLinksOnIconAliases(config) {
  return withAndroidManifest(config, (config) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(config.modResults);
    const aliases = app['activity-alias'] ?? [];
    if (aliases.length === 0) return config;

    const mainActivity = (app.activity ?? []).find(
      (a) => a.$?.['android:name'] === '.MainActivity'
    );
    const deepLinkFilters = (mainActivity?.['intent-filter'] ?? []).filter(isDeepLinkFilter);

    if (deepLinkFilters.length === 0) {
      // Louder than a silent no-op: reaching here means the filters moved or
      // were renamed, and shipping the build anyway is what caused the bug
      // this function exists to fix.
      throw new Error(
        'withAdaptiveDynamicIcons: .MainActivity has no intent-filter with <data>, so there are no deep-link filters to copy onto the icon aliases. Deep links would break for any user whose app icon changes. Check the scheme in app.json.'
      );
    }

    for (const alias of aliases) {
      const existing = alias['intent-filter'] ?? [];
      // Idempotent: prebuild runs this repeatedly, and a fresh prebuild
      // regenerates the aliases from scratch.
      alias['intent-filter'] = [
        ...existing.filter((f) => !isDeepLinkFilter(f)),
        ...JSON.parse(JSON.stringify(deepLinkFilters)),
      ];
    }

    return config;
  });
}

module.exports = function withAdaptiveDynamicIcons(config, props) {
  const icons = iconsFromProps(props);
  if (icons.length === 0) {
    throw new Error(
      'withAdaptiveDynamicIcons: no icons given. Pass the same object as the expo-dynamic-app-icon plugin, e.g. ["./plugins/withAdaptiveDynamicIcons", { bowl_empty: { image: "./assets/..." } }].'
    );
  }
  for (const [name, image] of icons) {
    if (!image) {
      throw new Error(
        `withAdaptiveDynamicIcons: icon "${name}" has no image path. The adaptive XML references @drawable/${name}_base, which is copied from that image — pass the same { image } config as the expo-dynamic-app-icon plugin.`
      );
    }
  }

  const includeMonochrome = !!config.android?.adaptiveIcon?.monochromeImage;

  // Manifest first, so the aliases carry deep links regardless of what the
  // dangerous mod below does to the icon resources.
  config = withDeepLinksOnIconAliases(config);

  return withDangerousMod(config, [
    'android',
    async (config) => {
      const anydpiFolder = path.join(config.modRequest.platformProjectRoot, ...ANYDPI_FOLDER);
      const nodpiFolder = path.join(config.modRequest.platformProjectRoot, ...NODPI_FOLDER);
      await fs.promises.mkdir(anydpiFolder, { recursive: true });
      await fs.promises.mkdir(nodpiFolder, { recursive: true });

      for (const [iconName, image] of icons) {
        const sourcePath = path.join(config.modRequest.projectRoot, image);
        await fs.promises.copyFile(sourcePath, path.join(nodpiFolder, `${iconName}_base.png`));
        await fs.promises.writeFile(
          path.join(anydpiFolder, `${iconName}.xml`),
          adaptiveIconXml(iconName, includeMonochrome),
          'utf8'
        );
      }

      return config;
    },
  ]);
};
