const path = require('path');
const fs = require('fs');
const { withDangerousMod } = require('@expo/config-plugins');

// expo-dynamic-app-icon (v1.2.0, unmaintained) writes each dynamic icon as a
// plain bitmap into mipmap-{m,h,x,xx,xxx}dpi and points the generated
// <activity-alias android:icon="@mipmap/<name>"> at it. It never emits an
// adaptive-icon XML, so on Android 8+ every dynamic variant is a *legacy*
// icon — and launchers give legacy icons the "legacy treatment": shrink the
// bitmap and composite it on a white backdrop masked to the device shape.
//
// That is the "bowl shows in a small square inside a larger white circle"
// report: our source art is already a full-bleed purple square with the bowl
// occupying only its middle ~40%, so the launcher shrank that whole purple
// square onto white, leaving a small square floating in a white circle.
//
// This plugin adds the missing mipmap-anydpi-v26/<name>.xml for each variant
// so Android treats them as adaptive icons like the default one, which is
// what stops the white-circle treatment.
//
// Both layers deliberately point at the same @mipmap/<name> bitmap. That
// mirrors exactly how this app's *default* icon is already configured —
// app.json's adaptiveIcon foregroundImage and backgroundImage are the same
// byte-identical file (assets/images/android-icon-{foreground,background}
// .png and icon.png all have md5 3e80c5ea...) — an opaque, full-bleed purple
// square. Because the source art is opaque and full-bleed, the foreground
// covers the background entirely and the result renders identically to the
// default icon, just with the current bowl. Splitting them into a
// transparent foreground over a purple background would look better still
// (the bowl could then fill the 66/108dp safe zone instead of sitting small
// and centred), but that needs new artwork rather than a build-time change,
// and would make the dynamic variants inconsistent with the default icon
// they swap in and out of.
//
// Runs as a dangerous mod like expo-dynamic-app-icon's own image step, but
// is deliberately order-independent of it: that plugin's cleanup pass only
// deletes non-"ic_launcher" files from the five density folders listed in
// its androidFolderNames, and mipmap-anydpi-v26 is not among them, so these
// XML files are never swept away no matter which plugin runs first.

const ANYDPI_FOLDER = ['app', 'src', 'main', 'res', 'mipmap-anydpi-v26'];

/** Expo's own icon step writes this from adaptiveIcon.monochromeImage; only
 * referenced when the app actually configures one, since pointing at a
 * missing drawable is a hard resource-linking failure at build time. */
const MONOCHROME_RESOURCE = 'ic_launcher_monochrome';

function adaptiveIconXml(iconName, includeMonochrome) {
  const monochromeLine = includeMonochrome
    ? `\n    <monochrome android:drawable="@mipmap/${MONOCHROME_RESOURCE}"/>`
    : '';
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by apps/mobile/plugins/withAdaptiveDynamicIcons.js — do not edit by hand. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/${iconName}"/>
    <foreground android:drawable="@mipmap/${iconName}"/>${monochromeLine}
</adaptive-icon>
`;
}

/** Accepts the same prop shape expo-dynamic-app-icon does (a record of
 * name -> { image }, or an array), so the icon names stay declared in one
 * place in app.json rather than duplicated here. */
function iconNamesFromProps(props) {
  if (!props) return [];
  if (Array.isArray(props)) return props.map((_, i) => String(i));
  return Object.keys(props);
}

module.exports = function withAdaptiveDynamicIcons(config, props) {
  const iconNames = iconNamesFromProps(props);
  if (iconNames.length === 0) {
    throw new Error(
      'withAdaptiveDynamicIcons: no icon names given. Pass the same object as the expo-dynamic-app-icon plugin, e.g. ["./plugins/withAdaptiveDynamicIcons", { bowl_empty: {...} }].'
    );
  }

  const includeMonochrome = !!config.android?.adaptiveIcon?.monochromeImage;

  return withDangerousMod(config, [
    'android',
    async (config) => {
      const folder = path.join(config.modRequest.platformProjectRoot, ...ANYDPI_FOLDER);
      await fs.promises.mkdir(folder, { recursive: true });

      for (const iconName of iconNames) {
        await fs.promises.writeFile(
          path.join(folder, `${iconName}.xml`),
          adaptiveIconXml(iconName, includeMonochrome),
          'utf8'
        );
      }

      return config;
    },
  ]);
};
